services:
  - type: web
    name: oshrireel
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: oshrireel-data
      mountPath: /app/output
      sizeGB: 5
